seed_everything: 0

data:
  class_path: LandCoverAIDataModule
  dict_kwargs:
    root: data/landcoverai
    download: true
  init_args:
    batch_size: 32
    num_workers: 2

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    class_names:
      - Background
      - Building
      - Woodland
      - Water
      - Road
    class_weights:
      - 0.02
      - 0.65
      - 0.04
      - 0.1
      - 0.4
    freeze_backbone: True
    ignore_index: -1
    loss: ce
    lr: 5e-4
    model_args:
      backbone: prithvi_vit_100
      decoder: UperNetDecoder
      decoder_channels: 256
      head_dropout: 0.1
      in_channels: 3
      num_classes: 5
      num_frames: 1
      pretrained: true
      bands:
        - RED
        - GREEN
        - BLUE
      decoder_scale_modules: True
    model_factory: PrithviModelFactory
    plot_on_val: 1

trainer:
  accelerator: gpu
  strategy: auto
  devices: 1
  num_nodes: 1
  precision: 16-mixed
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: output/ml4earth
      name: ml4earth 
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: EarlyStopping
      init_args:
        monitor: val/loss
        patience: 20
        min_delta: 0.00
    - class_path : ModelCheckpoint
      init_args:
        save_top_k: 1
        save_last: True
        
  max_epochs: 5
  check_val_every_n_epoch: 1
  log_every_n_steps: 10
  enable_checkpointing: true
  default_root_dir: output/ml4earth
    
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.e-4
    weight_decay: 0.05